[package]
name = "rohditor-gpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
half.workspace = true
rohditor-core = { path = "../core" }
rohditor-demosaic = { path = "../demosaic" }
rohditor-edit = { path = "../edit" }
rohditor-image = { path = "../image" }
rohditor-raw = { path = "../raw" }
thiserror.workspace = true
wgpu.workspace = true

[dev-dependencies]
pollster.workspace = true
