[package]
name = "rohditor-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
eframe.workspace = true
image.workspace = true
rfd.workspace = true
rohditor-core = { path = "../../crates/core" }
rohditor-raw = { path = "../../crates/raw" }
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
